sim:
	cp ./scr/runsim.sh runsim.sh
	./runsim.sh
	rm runsim.sh
dump:
	cp ./scr/wave.sh wave.sh
	./wave.sh
	rm wave.sh
clear:
	touch runsim.sh
	rm runsim.sh
	touch wave.sh
	rm wave.sh
all:
	make sim
	make dump
