##############################################################
#
# This file includes all the test targets as well as all the
# non-default build rules and test recipes.
#
##############################################################
#DEBUG := 1

##############################################################
#
# Test targets
#
##############################################################

###### Place all generic definitions here ######

# This defines tests which run tools of the same name.  This is simply for convenience to avoid
# defining the test name twice (once in TOOL_ROOTS and again in TEST_ROOTS).
# Tests defined here should not be defined in TOOL_ROOTS and TEST_ROOTS.
TEST_TOOL_ROOTS := mcs

# This defines the tests to be run that were not already defined in TEST_TOOL_ROOTS.
TEST_ROOTS :=

# This defines a list of tests that should run in the "short" sanity. Tests in this list must also
# appear either in the TEST_TOOL_ROOTS or the TEST_ROOTS list.
# If the entire directory should be tested in sanity, assign TEST_TOOL_ROOTS and TEST_ROOTS to the
# SANITY_SUBSET variable in the tests section below (see example in makefile.rules.tmpl).
SANITY_SUBSET :=

# This defines the tools which will be run during the the tests, and were not already defined in
# TEST_TOOL_ROOTS.
TOOL_ROOTS :=

# This defines the static analysis tools which will be run during the the tests. They should not
# be defined in TEST_TOOL_ROOTS. If a test with the same name exists, it should be defined in
# TEST_ROOTS.
# Note: Static analysis tools are in fact executables linked with the Pin Static Analysis Library.
# This library provides a subset of the Pin APIs which allows the tool to perform static analysis
# of an application or dll. Pin itself is not used when this tool runs.
SA_TOOL_ROOTS :=

# This defines all the applications that will be run during the tests.
APP_ROOTS :=

# This defines any additional object files that need to be compiled.
OBJECT_ROOTS :=

# This defines any additional dlls (shared objects), other than the pintools, that need to be compiled.
DLL_ROOTS :=

# This defines any static libraries (archives), that need to be built.
LIB_ROOTS :=
##/lib/x86_64-linux-gnu/libstdc++.so.6


##############################################################
#
# Test recipes
#
##############################################################

# This section contains recipes for tests other than the default.
# See makefile.default.rules for the default test rules.
# All tests in this section should adhere to the naming convention: <testname>.test


##############################################################
#
# Build rules
#
##############################################################


SRCS := SMPCache.cpp MultiCacheSim.cpp CacheCore.cpp Snippets.cpp nanassert.cpp MultiCacheSim_PinDriver.cpp
FACSRCS := MSI_SMPCache.cpp MESI_SMPCache.cpp

OBJS := $(SRCS:$(OBJDIR)/%.cpp=$(OBJDIR)%.$(OBJ_SUFFIX))
FACOBJS := $(FACSRCS:%.cpp=%.so)

# This section contains the build rules for all binaries that have special build rules.
# See makefile.default.rules for the default build rules.


#####Tool_flags already exists. apppeding the DPIN behind
##################################################
TOOL_CXXFLAGS += -DPIN 
TOOL_CXXFLAGS_NOOPT += -DPIN 

TOOL_LDFLAGS_NOOPT+= -ldl
#######################################################

$(OBJDIR)SMPCache$(OBJ_SUFFIX) : SMPCache.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) -g $(COMP_OBJ)$@ $< 

$(OBJDIR)MultiCacheSim$(OBJ_SUFFIX) : MultiCacheSim.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) -g  $(COMP_OBJ)$@ $<

$(OBJDIR)CacheCore$(OBJ_SUFFIX) : CacheCore.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) -g  $(COMP_OBJ)$@ $<

$(OBJDIR)Snippets$(OBJ_SUFFIX) : Snippets.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) -g  $(COMP_OBJ)$@ $<

$(OBJDIR)nanassert$(OBJ_SUFFIX) : nanassert.cpp
	$(CXX) -Wno-deprecated  -g $(TOOL_CXXFLAGS_NOOPT) $(COMP_OBJ)$@ $<

$(OBJDIR)MultiCacheSim_PinDriver$(OBJ_SUFFIX) : MultiCacheSim_PinDriver.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT) -g $(COMP_OBJ)$@ $< 



#####################################  MOESI
$(OBJDIR)MOESI_SMPCache$(OBJ_SUFFIX) : MOESI_SMPCache.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT)  -g $(COMP_OBJ)$@ $< 

$(OBJDIR)MOESI_SMPCache$(PINTOOL_SUFFIX) : $(OBJDIR)MOESI_SMPCache$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)  $(OBJDIR)CacheCore$(OBJ_SUFFIX) $(OBJDIR)Snippets$(OBJ_SUFFIX) $(OBJDIR)nanassert$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS_NOOPT) -fPIC -shared  $(OBJDIR)MOESI_SMPCache$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)  $(OBJDIR)CacheCore$(OBJ_SUFFIX) $(OBJDIR)Snippets$(OBJ_SUFFIX) $(OBJDIR)nanassert$(OBJ_SUFFIX) $(LINK_EXE)$@  $(TOOL_LPATHS) $(TOOL_LIBS) 




##################################### no filter in MESI
$(OBJDIR)MESI_SMPCache$(OBJ_SUFFIX) : MESI_SMPCache.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT)  -g $(COMP_OBJ)$@ $< 
#	$(CXX) $(TOOL_CXXFLAGS)  -g $(COMP_OBJ)$@ $< 

$(OBJDIR)MESI_SMPCache$(PINTOOL_SUFFIX) : $(OBJDIR)MESI_SMPCache$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)  $(OBJDIR)CacheCore$(OBJ_SUFFIX) $(OBJDIR)Snippets$(OBJ_SUFFIX) $(OBJDIR)nanassert$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS_NOOPT) -fPIC -shared  $(OBJDIR)MESI_SMPCache$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)  $(OBJDIR)CacheCore$(OBJ_SUFFIX) $(OBJDIR)Snippets$(OBJ_SUFFIX) $(OBJDIR)nanassert$(OBJ_SUFFIX) $(LINK_EXE)$@  $(TOOL_LPATHS) $(TOOL_LIBS) 


###################################  MSI with filter
$(OBJDIR)MSI_SMPCache$(OBJ_SUFFIX) : MSI_SMPCache.cpp
	$(CXX) $(TOOL_CXXFLAGS_NOOPT)  -g $(COMP_OBJ)$@ $< 

$(OBJDIR)MSI_SMPCache$(PINTOOL_SUFFIX) : $(OBJDIR)MSI_SMPCache$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)  $(OBJDIR)CacheCore$(OBJ_SUFFIX) $(OBJDIR)Snippets$(OBJ_SUFFIX) $(OBJDIR)nanassert$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS_NOOPT) -fPIC -shared  $(OBJDIR)MSI_SMPCache$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)  $(OBJDIR)CacheCore$(OBJ_SUFFIX) $(OBJDIR)Snippets$(OBJ_SUFFIX) $(OBJDIR)nanassert$(OBJ_SUFFIX) $(LINK_EXE)$@  $(TOOL_LPATHS) $(TOOL_LIBS) 



################################# main simulation : mcs 
$(OBJDIR)mcs$(PINTOOL_SUFFIX) : $(OBJDIR)MultiCacheSim_PinDriver$(OBJ_SUFFIX)  $(OBJDIR)MultiCacheSim$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)
	$(LINKER) $(TOOL_LDFLAGS_NOOPT)  -fPIC -shared $(OBJDIR)MultiCacheSim_PinDriver$(OBJ_SUFFIX)  $(OBJDIR)MultiCacheSim$(OBJ_SUFFIX) $(OBJDIR)SMPCache$(OBJ_SUFFIX)  $(OBJDIR)CacheCore$(OBJ_SUFFIX) $(OBJDIR)Snippets$(OBJ_SUFFIX) $(OBJDIR)nanassert$(OBJ_SUFFIX) $(LINK_EXE) $@ $(TOOL_LPATHS) $(TOOL_LIBS) -rdynamic




#-o $(OBJDIR)mcs$(PINTOOL_SUFFIX) $(TOOL_LPATHS) $(TOOL_LIBS)







